### ISSUE TITLE
Expand foreach

### ISSUE THREAD

**Issue by svdonuc** [vlad-jiman-sv/wonka-magic-gum#2]
foreach should always be in the form of
```
foreach ($items as $item) {
    # code
}
```

https://github.com/vlad-jiman-sv/wonka-magic-gum/blob/fbcdc01ea219b25dde51a381ed08feefe6cddb14/custom/clients/base/api/SQLToolApi.php#L69

**Comment by vlad-jiman-sv** [comment]
Modified the foreach

**Comment by svdonuc** [comment]
Please do so for all foreach blocks in this file

**Comment by vlad-jiman-sv** [comment]
Updated
