### ISSUE TITLE
Return format + unreachable exit

### ISSUE THREAD

**Issue by svdonuc** [vlad-jiman-sv/wonka-magic-gum#4]
```
return($return);
exit;
```

should be simply
`return $return;`

https://github.com/vlad-jiman-sv/wonka-magic-gum/blob/fbcdc01ea219b25dde51a381ed08feefe6cddb14/custom/clients/base/api/SQLToolApi.php#L73

**Comment by vlad-jiman-sv** [comment]
Removed the exit and modified the return.

**Comment by svdonuc** [comment]
Still 2 more actions to be done:
1) Correct the final return also to be a statement, not a function call

**Comment by svdonuc** [comment]
2. return array('Error' => 'no arg');  should be something like throw new  SugarApiException('foobar err message');

**Comment by vlad-jiman-sv** [comment]
Corrected points 1 and 2.
