### ISSUE TITLE
Use exit with caution

### ISSUE THREAD

**Issue by svdonuc** [vlad-jiman-sv/wonka-magic-gum#6]
We should not use 'exit' or 'die' in code that is not top-level.
instead, we should always return or throw an exception.

https://github.com/vlad-jiman-sv/wonka-magic-gum/blob/fbcdc01ea219b25dde51a381ed08feefe6cddb14/custom/clients/base/api/SQLToolApi.php#L88

**Comment by vlad-jiman-sv** [comment]
Removed the exit, added a throw new Exception in its place.
