### ISSUE TITLE
No point in building the return

### ISSUE THREAD

**Issue by svdonuc** [vlad-jiman-sv/wonka-magic-gum#7]
As we are using the exception mechanism instead of returning, there is no reason to add info to the $return array.
Instead, add the $ac->db->lastDbError() value to the Exception message

https://github.com/vlad-jiman-sv/wonka-magic-gum/blob/b3f10960624c0f6476c3eeb79ac0d6a47e73d2f5/custom/clients/base/api/SQLToolApi.php#L84

**Comment by vlad-jiman-sv** [comment]
Included the lastDbError in the Exception.
