### ISSUE TITLE
PHP source code should not end with ?>

### ISSUE THREAD

**Issue by svdonuc** [vlad-jiman-sv/wonka-magic-gum#8]
Unlike in the php template files, where we are mixing output and php snippets, php-only files should not end with "?>".
https://github.com/vlad-jiman-sv/wonka-magic-gum/blob/b3f10960624c0f6476c3eeb79ac0d6a47e73d2f5/custom/clients/base/api/SQLToolApi.php#L109

**Comment by svdonuc** [comment]
Rationale explained here: https://stackoverflow.com/questions/3219383/why-do-some-scripts-omit-the-closing-php-tag

**Comment by vlad-jiman-sv** [comment]
Removed the closing tag and read the explanation :D
